In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1 = pd.read_csv('heart.csv')
df2 = pd.read_csv('AirQuality.csv',sep=';')

In [4]:
# a.data cleaning
df1.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,patient_id
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0,1.0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0,2.0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0,3.0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0,5.0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0,8.0

In [11]:
print(df1.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
print(df1.shape)

(1025, 14)

df1 = df1.drop(['patient_id'], axis=1)

In [14]:
df1 = df1.drop(['target'], axis=1)

In [15]:
df1.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2

In [5]:
print(df2.isnull().sum())

Date             114
Time             114
CO(GT)           114
PT08.S1(CO)      114
NMHC(GT)         114
C6H6(GT)         114
PT08.S2(NMHC)    114
NOx(GT)          114
PT08.S3(NOx)     114
NO2(GT)          114
PT08.S4(NO2)     114
PT08.S5(O3)      114
T                114
RH               114
AH               114
dtype: int64

In [18]:
#Removing duplicates
df2.dropna(inplace=True) 
df2.drop_duplicates(inplace=True)
df2.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578"
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255"
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502"
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867"
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888"

In [11]:
# b.Data integration
merged_df = pd.merge(df1, df2,left_index=True, right_index=True)
merged_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,...,C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,52,1,0,125,212,0,1,168,0,1.0,...,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578"
1,53,1,0,140,203,1,0,155,1,3.1,...,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255"
2,70,1,0,145,174,0,1,125,1,2.6,...,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502"
3,61,1,0,148,203,0,1,161,0,0.0,...,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867"
4,62,0,0,138,294,1,1,106,0,1.9,...,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888"

In [24]:
# c.data transformation
columns_to_drop = ['sex', 'cp','fbs']
transformed_df = df1.drop(columns_to_drop, axis=1)
transformed_df.head()

,age,trestbps,chol,restecg,thalach,exang,oldpeak,slope,ca,thal,target,patient_id
0,52,125,212,1,168,0,1.0,2,2,3,0,1.0
1,53,140,203,0,155,1,3.1,0,0,3,0,2.0
2,70,145,174,1,125,1,2.6,0,0,3,0,3.0
3,61,148,203,1,161,0,0.0,2,1,3,0,5.0
4,62,138,294,1,106,0,1.9,1,3,2,0,8.0

In [ ]:
#*****************************************************************************

In [ ]:
#*****************************************************************************

In [ ]:
#*****************************************************************************

In [94]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [98]:
df1 = pd.read_csv('heart.csv')
df2 = pd.read_csv('AirQuality.csv',sep=';')

merged_df = pd.merge(df1, df2,left_index=True, right_index=True)
merged_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,...,NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,52,1,0,125,212,0,1,168,0,1.0,...,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,53,1,0,140,203,1,0,155,1,3.1,...,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,70,1,0,145,174,0,1,125,1,2.6,...,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,61,1,0,148,203,0,1,161,0,0.0,...,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,62,0,0,138,294,1,1,106,0,1.9,...,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN

In [96]:
# a.data transformation
columns_to_drop = ['sex', 'cp','fbs']
transformed_df = df1.drop(columns_to_drop, axis=1)
transformed_df.head()

,age,trestbps,chol,restecg,thalach,exang,oldpeak,slope,ca,thal,target,patient_id
0,52,125,212,1,168,0,1.0,2,2,3,0,1.0
1,53,140,203,0,155,1,3.1,0,0,3,0,2.0
2,70,145,174,1,125,1,2.6,0,0,3,0,3.0
3,61,148,203,1,161,0,0.0,2,1,3,0,5.0
4,62,138,294,1,106,0,1.9,1,3,2,0,8.0

In [100]:
#b.error correcting
correctdf = df1.drop(['sex','cp','ca','thal'],axis=1)
correctdf

,age,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,target,patient_id
0,52,125,212,0,1,168,0,1.0,2,0,1.0
1,53,140,203,1,0,155,1,3.1,0,0,2.0
2,70,145,174,0,1,125,1,2.6,0,0,3.0
3,61,148,203,0,1,161,0,0.0,2,0,5.0
4,62,138,294,1,1,106,0,1.9,1,0,8.0
...,...,...,...,...,...,...,...,...,...,...,...
1020,59,140,221,0,1,164,1,0.0,2,1,NaN
1021,60,125,258,0,0,141,1,2.8,1,0,NaN
1022,47,110,275,0,0,118,1,1.0,1,0,NaN
1023,50,110,254,0,0,159,0,0.0,2,1,NaN
1024,54,120,188,0,1,113,0,1.4,1,0,NaN

In [101]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [68]:
#e.Data model building
X = df1.drop('age', axis=1)
y = df1['age']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [87]:
# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')  # or 'median', 'most_frequent', etc.
X_train_imputed = imputer.fit_transform(X_train_scaled)
X_test_imputed = imputer.fit_transform(X_test_scaled)




X_train.head()

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,patient_id
835,1,2,118,149,0,0,126,0,0.8,2,3,2,0,NaN
137,0,0,180,325,0,1,154,1,0.0,2,0,2,1,5.009530e+28
534,0,2,108,267,0,0,167,0,0.0,2,0,2,1,NaN
495,1,0,135,234,0,1,161,0,0.5,1,0,3,1,NaN
244,1,2,125,245,1,0,166,0,2.4,1,0,2,1,NaN

In [83]:
model = LogisticRegression()
model.fit(X_train_imputed, y_train)

LogisticRegression()

In [88]:
accuracy = model.score(X_test_imputed, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.2146341463414634

In [89]:
from sklearn.metrics import confusion_matrix

In [91]:
output = model.predict(X_test_imputed)

In [92]:
cm = confusion_matrix(y_test, output)

In [93]:
print(cm)

[[1 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]